/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SkillEditorRouteImport } from './routes/skill-editor'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ObserveRouteImport } from './routes/observe'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AllowlistRouteImport } from './routes/allowlist'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicExtensionSyncRouteImport } from './routes/api/public/extension-sync'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillEditorRoute = SkillEditorRouteImport.update({
  id: '/skill-editor',
  path: '/skill-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ObserveRoute = ObserveRouteImport.update({
  id: '/observe',
  path: '/observe',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AllowlistRoute = AllowlistRouteImport.update({
  id: '/allowlist',
  path: '/allowlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionSyncRoute = ApiPublicExtensionSyncRouteImport.update({
  id: '/api/public/extension-sync',
  path: '/api/public/extension-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/allowlist': typeof AllowlistRoute
  '/config': typeof ConfigRoute
  '/database': typeof DatabaseRoute
  '/extension': typeof ExtensionRoute
  '/observe': typeof ObserveRoute
  '/playground': typeof PlaygroundRoute
  '/skill-editor': typeof SkillEditorRoute
  '/skills': typeof SkillsRoute
  '/tracker': typeof TrackerRoute
  '/api/public/extension-sync': typeof ApiPublicExtensionSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/allowlist': typeof AllowlistRoute
  '/config': typeof ConfigRoute
  '/database': typeof DatabaseRoute
  '/extension': typeof ExtensionRoute
  '/observe': typeof ObserveRoute
  '/playground': typeof PlaygroundRoute
  '/skill-editor': typeof SkillEditorRoute
  '/skills': typeof SkillsRoute
  '/tracker': typeof TrackerRoute
  '/api/public/extension-sync': typeof ApiPublicExtensionSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/allowlist': typeof AllowlistRoute
  '/config': typeof ConfigRoute
  '/database': typeof DatabaseRoute
  '/extension': typeof ExtensionRoute
  '/observe': typeof ObserveRoute
  '/playground': typeof PlaygroundRoute
  '/skill-editor': typeof SkillEditorRoute
  '/skills': typeof SkillsRoute
  '/tracker': typeof TrackerRoute
  '/api/public/extension-sync': typeof ApiPublicExtensionSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/allowlist'
    | '/config'
    | '/database'
    | '/extension'
    | '/observe'
    | '/playground'
    | '/skill-editor'
    | '/skills'
    | '/tracker'
    | '/api/public/extension-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/allowlist'
    | '/config'
    | '/database'
    | '/extension'
    | '/observe'
    | '/playground'
    | '/skill-editor'
    | '/skills'
    | '/tracker'
    | '/api/public/extension-sync'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/allowlist'
    | '/config'
    | '/database'
    | '/extension'
    | '/observe'
    | '/playground'
    | '/skill-editor'
    | '/skills'
    | '/tracker'
    | '/api/public/extension-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AllowlistRoute: typeof AllowlistRoute
  ConfigRoute: typeof ConfigRoute
  DatabaseRoute: typeof DatabaseRoute
  ExtensionRoute: typeof ExtensionRoute
  ObserveRoute: typeof ObserveRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SkillEditorRoute: typeof SkillEditorRoute
  SkillsRoute: typeof SkillsRoute
  TrackerRoute: typeof TrackerRoute
  ApiPublicExtensionSyncRoute: typeof ApiPublicExtensionSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-editor': {
      id: '/skill-editor'
      path: '/skill-editor'
      fullPath: '/skill-editor'
      preLoaderRoute: typeof SkillEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observe': {
      id: '/observe'
      path: '/observe'
      fullPath: '/observe'
      preLoaderRoute: typeof ObserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allowlist': {
      id: '/allowlist'
      path: '/allowlist'
      fullPath: '/allowlist'
      preLoaderRoute: typeof AllowlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension-sync': {
      id: '/api/public/extension-sync'
      path: '/api/public/extension-sync'
      fullPath: '/api/public/extension-sync'
      preLoaderRoute: typeof ApiPublicExtensionSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AllowlistRoute: AllowlistRoute,
  ConfigRoute: ConfigRoute,
  DatabaseRoute: DatabaseRoute,
  ExtensionRoute: ExtensionRoute,
  ObserveRoute: ObserveRoute,
  PlaygroundRoute: PlaygroundRoute,
  SkillEditorRoute: SkillEditorRoute,
  SkillsRoute: SkillsRoute,
  TrackerRoute: TrackerRoute,
  ApiPublicExtensionSyncRoute: ApiPublicExtensionSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
